name: rtm
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - ipython
  - jupyterlab
  - obspy
  - pip
#  - pygmt  # OPTIONAL
  - rioxarray
  - tqdm
  - pip:
    - git+https://github.com/uafgeotools/waveform_collection.git
    - --editable .
